version: "3"

services: 
    flask:
        build: .
        ports:
            - 5000:5000
        volumes:
            - .:/app
    mysql:
        image: mysql
        command: mysqld --default-authentication-plugin=mysql_native_password
        environment: 
            MYSQL_ROOT_PASSWORD: root
        volumes: 
            - mysql_data:/var/lib/mysql
        ports: 
            - 9997:3306
volumes:
    mysql_data: